### PR TITLE
support -I and -b options to locate a preparer (fix #8)

### LINKED ISSUE #8: Would be nice if this plugin also respects -I and -b options
This plugin respects -l option to find a preparer package. It would be nice if it also respects -I option (and maybe -b option), as App::Prove does in _get_lib method, so that a preparer can be placed into t/lib and such.
https://metacpan.org/source/LEONT/Test-Harness-3.39/lib/App/Prove.pm#L572-590

In that method, additional libs are converted into absolute paths, too. 
https://rt.cpan.org/Public/Bug/Display.html?id=24926

The method has been existing since 3.00, though it's private.

### PR DESCRIPTION
**Pull request by charsbar**
Code is taken from App::Prove::_get_libs

### CODE REVIEW

**Comment by mackee** [comment]
Thanks!
Please wait a moment. I try to fix failing tests on travis now.

**Comment by mackee** [comment]
That problem fix in #10.

**Comment by mackee** [comment]
@charsbar I release contains this pull request now.

**Comment by charsbar** [comment]
@mackee Thank you!

**Pull request merged**
